### PR TITLE
Memberships Problem Fix

### LINKED ISSUE #64: The Memberships Problem
# Refactor Appointment Membership Flow (Patient Can Book Before Membership Exists)

## Type

Refactor / Feature

## Summary

The current appointment system incorrectly requires a patient to already exist in the `Memberships` table before they are allowed to browse clinics, browse doctors, or create an appointment request.

This creates a circular dependency:

* Patient must be a member first
* But intended design is that patient becomes a member **after** booking their first appointment

We are refactoring the membership lifecycle so that all users are added to `Memberships` at the correct business event, while patients can discover clinics/doctors first and become members after booking.

---

### 1. Clinic Admin Membership

When a clinic is approved, the owning clinic administrator must automatically be inserted into `Memberships`.

**Trigger Event:**

* Clinic approval status changes to approved

**Insert:**

```sql id="udud7g"
(clinic_id, admin_id)
```

---

### 2. Nurse Membership

When a nurse accepts an invitation from the clinic admin, the nurse must automatically be inserted into `Memberships`.

**Trigger Event:**

* `staff_permissions.invitation_status`
* `pending -> accepted`

**Insert:**

```sql id="4fbo56"
(clinic_id, nurse_user_id)
```

---

### 3. Doctor Membership

When a doctor accepts an invitation from the clinic admin, the doctor must automatically be inserted into `Memberships`.

**Trigger Event:**

* doctor invite accepted

**Insert:**

```sql id="7pcg5s"
(clinic_id, doctor_user_id)
```

---

### 4. Patient Membership

A patient should not need prior membership to book.

After a successful appointment request / booking, the patient becomes a member of that clinic.

**Trigger Event:**

* appointment successfully created

**Insert:**

```sql id="g3upm2"
(clinic_id, patient_user_id)
```

---

## Intended Correct Patient Flow

1. Patient logs in
2. Patient browses approved clinics
3. Patient selects clinic
4. Patient views available doctors
5. Patient books appointment
6. Patient is inserted into `Memberships`
7. Future visits and follow-ups use that relationship naturally

---

### Current Incorrect Behavior

`PatientAppointmentManager.tsx` currently loads clinics using only the patient's existing memberships.

This prevents first-time patients from booking.

Additionally, portions of the database logic still assume prior membership before appointment creation.

---

### Frontend Refactor

Update `PatientAppointmentManager.tsx`

Replace clinic-loading logic:

**Current**

```ts id="x9sz91"
Membership-based clinic discovery
```

**New**

```ts id="i2vt7y"
Approved clinics list
```

---

### Doctor Discovery Refactor

Patients must be able to see doctors assigned to a selected clinic without requiring prior membership.

Possible implementation:

* public-safe doctor directory view
* clinic doctor assignments query
* updated RLS policies

---

### Database Refactor

Create / update migrations so `Memberships` becomes event-driven.

Recommended automation:

* Trigger on clinic approval → add clinic admin
* Trigger on accepted nurse invite → add nurse
* Trigger on accepted doctor invite → add doctor
* Trigger on appointment creation → add patient

Use:

```sql id="tdkixd"
ON CONFLICT DO NOTHING
```

to prevent duplicates.

---

## Benefits

* Eliminates circular dependency bug
* Correctly models real clinic relationships
* Supports first-time patients
* Better onboarding for staff/admin users
* Cleaner role lifecycle
* Easier future reporting and permissions logic

---

## Files / Systems Likely Impacted

* `PatientAppointmentManager.tsx`
* Clinic approval flow
* Staff invitation system
* Doctor invitation flow
* Supabase triggers / migrations
* Appointment creation logic
* Membership queries
* RLS policies

---

### Membership Lifecycle

* Clinic admin added after clinic approval
* Nurse added after invite acceptance
* Doctor added after invite acceptance
* Patient added after first booking

### Booking Flow

* New patient with zero memberships can browse clinics
* New patient can view doctors
* New patient can book appointment

### Stability

* No duplicate membership rows
* Existing dashboards continue functioning
* No regressions in queue or appointment systems

---

## Notes

This issue converts `Memberships` into the central relationship table for all clinic participants and fixes the current booking architecture.

### PR DESCRIPTION
**Pull request by Kelvin205**
## Related Issue

Fixes #64

---

## Summary

Refactors ClinicIQ membership and appointment workflows so user-to-clinic relationships are created automatically based on real business actions instead of requiring manual membership setup.

This PR fixes the broken appointment prerequisite flow where patients previously needed clinic membership before booking, and improves clinic staff management by supporting direct doctor assignment through memberships.

---

## Changes Made

* Added database triggers to automatically insert patients into `Memberships` after successful appointment creation.
* Added database trigger logic to sync clinic administrators into `Memberships` when clinics are approved (including pre-approved SQL inserts).
* Added reverse sync behavior to remove clinic admin membership when clinic approval is revoked or admin changes.
* Updated patient appointment flow so patients can browse approved clinics and doctors before membership exists.
* Fixed patient appointment creation path and related RLS issues on `Appointments`.
* Updated `PatientAppointmentManager.tsx` appointment status handling to use valid enum values instead of deprecated `requested`.
* Refactored `ClinicManageStaff.tsx`:

  * Nurses continue using `staff_permissions`
  * Doctors are added directly to `Memberships`
  * Doctors now display properly in dashboard staff lists
  * Doctor removal also deletes corresponding membership rows
* Improved mixed staff UI behavior and sorting for nurses/doctors.

---

## Type of Change

Please select the relevant option:

* [ ] Bug fix
* [x] New feature
* [x] Enhancement
* [x] Refactor
* [ ] Documentation update

---

## Testing

* Ran frontend locally with Vite
* Tested patient can view clinics and doctors before membership exists
* Verified successful appointment creation inserts patient into `Memberships`
* Verified doctor added from clinic admin dashboard appears in UI
* Verified doctor removal deletes row from `Memberships`
* Verified clinic admin auto-membership on clinic approval
* Tested duplicate membership prevention behavior

---

## Checklist

Before submitting this PR, please confirm:

* [x] Code compiles and runs locally
* [x] No unnecessary console logs
* [x] Relevant issue is linked
* [x] Changes were tested
* [x] PR title clearly describes the change

---

## Additional Notes

This PR significantly improves the Memberships table as the central relationship model between users and clinics.

User membership is now created from actual workflow events:

* Patient books appointment → becomes clinic member
* Doctor assigned by clinic admin → becomes clinic member
* Nurse accepts invite → becomes clinic member
* Clinic approved → clinic admin becomes clinic member

This reduces manual setup requirements and aligns the database with intended ClinicIQ behavior.

### CODE REVIEW

**Review by kritanbaniya — APPROVED** [review]

File: frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx [hunk 1]
```diff
@@ -243,7 +243,7 @@ export default function PatientAppointmentManager() {
             date: `${yyyy}-${mm}-${dd}`,
             time: `${hh}:${min}`,  
             patientId: patientInfo.id,
-            appointment_status: 'requested' 
+            appointment_status: 'pending',
```
Comment (Untitled71) [inline frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx]: After the patient submits the form; it should be 'requested' or what is now 'unseen'. 

the term `Pending` is reserved for when a patient* needs to take action and make changes to their request. 
When it is unseen, the nurse needs to take action upon it. 

This does remind me that there are some changes i need to make in terms of the actions the patient can take on their pending appointments. 


Also the keyword `pending` seems ambigious, so i am open to recommendations on a better word that would convey this function.

Comment (Kelvin205) [reply frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx]: The value 'requested' is not supported in our current Supabase schema. 
It was changed to 'unseen' to prevent errors from occurring while running the application. 
the current status values supported by the appointment table are: 
image

File: frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx [hunk 2]
```diff
@@ -59,9 +59,8 @@ export default function PatientAppointmentManager() {
         } 
         const { data, error } = await supabase
             .schema('public')
-            .from('membernamerole')
-            .select('*')
-            .eq('user_id', authData.user.id) 
+            .from('clinics')
+            .select('*')
```
Comment (Untitled71) [inline frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx:63]: oh yeah; they cant see doctors unless they are a member of the clinic. 

so ig than the question, and thus problem, that arrises is: 
**'how do patients make appointments for clinics they are not already a part of?'**

The 2 solutions I can think of is 
changing the appointments page to allow for this,
or add that capability in the clinic discovery page.

Lmk when one yall think is best, or if the problem would be something else

File: frontend/src/pages/Dashboard/Nurse/NurseAppointmentManager.tsx [hunk 3]
```diff
@@ -242,7 +242,7 @@ export default function NurseAppointmentManager() {
         searchValue: '',
         showReqs: [ 
             'pending',
-            'requested',
+            'unseen',
```
Comment (Untitled71) [inline frontend/src/pages/Dashboard/Nurse/NurseAppointmentManager.tsx:245]: it's funny because this was the name I had for it before switch to `requested` LOL; this change seems fine, as long as it works everywhere.

**Review by Untitled71 — APPROVED** [review]

File: frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx (hunk 2 above)
Comment (Untitled71) [reply frontend/src/pages/Dashboard/Patient/PatientAppointmentManager.tsx:63]: clinics works!
